apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "todo-app.fullname" . }}-frontend
  labels:
    app: {{ include "todo-app.fullname" . }}-frontend
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "todo-app.fullname" . }}-frontend
  template:
    metadata:
      labels:
        app: {{ include "todo-app.fullname" . }}-frontend
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.frontend.service.port }}
          env:
            - name: BACKEND_URL
              value: "{{ .Values.config.backendURL }}"
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}