apiVersion: v1
kind: Secret
metadata:
  name: {{ include "todo-app.fullname" . }}-secrets
type: Opaque
stringData:
  OPENAI_API_KEY: {{ .Values.secrets.OPENAI_API_KEY | quote }}
  GROQ_API_KEY: {{ .Values.secrets.GROQ_API_KEY | quote }}
  DATABASE_URL: {{ .Values.secrets.DATABASE_URL | quote }}